export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const ADJUST_SEAT = 'ADJUST_SEAT';
export const SEARCH_FROM_DATA = 'SEARCH_FROM_DATA';
export const LOAD_CURRENT_ITEM = 'LOAD_CURRENT_ITEM';
export const LIST_ITEMS = 'LIST_ITEMS';
